<script>

  /*,若不传入回调函数，则会返回一个 promise,mongose vue的$nexttick 都是这样做的------------------------------*/

  const i = 0

  function asynFn(callback) {

    const promise = new Promise((resolve, reject) => {
      if (i > 0) {
        setTimeout(() => {
          resolve(i + 1)
        }, 500)
      } else {
        reject(new Error('err'))
      }

    })
    if (callback) {

      promise.then(res => {
        callback(false, res)
      })
        .catch(err => {
          callback(err)
        })
    } else {
      return promise
    }
  }


  asynFn((err, res) => {
    if (err) {
      console.log(err)
    } else {
      console.log(res)

    }

  })


  asynFn().then(res => console.log(res)).catch(err => {
    console.log(err)
  })


</script>
