<script>
  const i = 0

  function f() {
    return new Promise((resolve, reject) => {
      if (i > 0) {
        resolve(1)
      } else {
        reject(new Error(0))
      }
    })
  }

  f().then(res => console.log(res))
    .catch(err => console.log('err', err))

</script>
